language: node_js
node_js:
  - "6.9.1"
# safelist
branches:
  only:
  - develop
script:
  - ./node_modules/istanbul/lib/cli.js cover --config ./istanbul.yml ./node_modules/mocha/bin/_mocha ./TEST/UNIT/ --report lcovonly -- -R spec && ./node_modules/.bin/codecov
